- name: Configurar e usar o ambiente virtual do Python (tanto local quanto no server)
  hosts: all, localhost
  gather_facts: false

  tasks:
    - name: Verificar se o ambiente virtual .venv existe
      ansible.builtin.stat:
        path: .venv
      register: venv_exists

    - name: Criar o ambiente virtual .venv se não existir
      ansible.builtin.command: python3 -m venv .venv
      when: not venv_exists.stat.exists
      changed_when: true

    - name: Configurar ansible_python_interpreter para usar .venv
      ansible.builtin.set_fact:
        ansible_python_interpreter: ".venv/bin/python"

- name: Instala requisitos locais
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Instala ansible-builder
      ansible.builtin.pip:
        name: ansible-builder
        state: present

    - name: Instala ansible-navigator
      ansible.builtin.pip:
        name: ansible-navigator
        state: present

    - name: Instala ansible-lint
      ansible.builtin.pip:
        name: ansible-lint
        state: present

    - name: Instala coleções do Ansible
      ansible.builtin.command: >
        ansible-galaxy install -r requirements/ansible-requirements.yml
      changed_when: false

- name: Instala e configura o MySQL
  hosts: all
  become: true

  tasks:
    - name: Instala pip3
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Instala PyMySQL
      ansible.builtin.pip:
        name: PyMySQL
        state: present

    - name: Instalar cryptography
      ansible.builtin.pip:
        name: cryptography
        state: present

    - name: Adicionar repositório MySQL em RedHat
      ansible.builtin.yum_repository:
        name: mysql84-community
        description: MySQL 8.4 Community repo
        baseurl: https://repo.mysql.com/yum/mysql-8.4-community/el/9/x86_64/
        gpgcheck: false
        state: present
      when: ansible_os_family == "RedHat"

    - name: Instalar MySQL usando package
      ansible.builtin.package:
        name: mysql-community-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Iniciar MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: Aguardar MySQL iniciar e estar disponível
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: 3306
        delay: 3
        timeout: 300
        state: started

    - name: Verificar se a senha do root precisa ser alterada
      ansible.builtin.shell: >
        mysql -u root -e "SELECT 1;"
      environment:
        MYSQL_PWD: "{{ mysql_root_password }}"
      register: root_password_check
      failed_when: false
      changed_when: false
      ignore_errors: true

    - name: Definir variável para alterar a senha do root
      ansible.builtin.set_fact:
        alter_root_password: true
      when: root_password_check.rc != 0

    - name: Obter a senha temporária do root do MySQL
      ansible.builtin.shell: "set -o pipefail && grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
      register: mysql_temp_root_password
      no_log: true
      changed_when: mysql_temp_root_password.stdout != ""
      when: alter_root_password | default(false)

    - name: Redefinir a senha do root do MySQL diretamente usando mysql
      ansible.builtin.shell: >
            mysql --connect-expired-password -u root -e "
                  ALTER USER 'root'@'localhost'
                  IDENTIFIED WITH caching_sha2_password BY '{{ mysql_root_password }}'
                  PASSWORD EXPIRE NEVER;"
      register: alter_user_result
      no_log: true
      environment:
        MYSQL_PWD: "{{ mysql_temp_root_password.stdout }}"
      changed_when: "'changed' in alter_user_result.stdout"
      when: alter_root_password | default(false)
      notify: Recarregar tabelas de privilégios

    - name: Remover usuários anônimos
      community.mysql.mysql_user:
        name: ''
        host_all: true
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Desabilitar logins remotos do root
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      loop:
        - "{{ ansible_fqdn }}"
        - "{{ inventory_hostname }}"
        - 127.0.0.1
        - ::1

    - name: Remover banco de dados de teste
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Cria database dev
      community.mysql.mysql_db:
        name: abnmo_dev
        encoding: utf8
        collation: utf8_general_ci
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Cria database homolog
      community.mysql.mysql_db:
        name: abnmo_qa
        encoding: utf8
        collation: utf8_general_ci
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Cria admin (o mesmo para dev e QA)
      ansible.builtin.shell: >
        mysql -u root -p{{ mysql_root_password }} -e "
            CREATE USER IF NOT EXISTS 'abnmo_admin'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ lookup('file', 'secrets/abnmo_admin_pwd.txt') }}';
            GRANT ALL PRIVILEGES ON abnmo_dev.* TO 'abnmo_admin'@'%';
            GRANT ALL PRIVILEGES ON abnmo_qa.* TO 'abnmo_admin'@'%';
            FLUSH PRIVILEGES;"
      register: create_admin_result
      changed_when: create_admin_result.rc == 0
      no_log: true

    - name: Cria usuário dev
      ansible.builtin.shell: >
        mysql -u root -p{{ mysql_root_password }} -e "
            CREATE USER IF NOT EXISTS 'abnmo_dev'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ lookup('file', 'secrets/abnmo_dev_pwd.txt') }}';
            GRANT DELETE, INSERT, SELECT, UPDATE ON abnmo_dev.* TO 'abnmo_dev'@'%';
            FLUSH PRIVILEGES;"
      register: create_dev_user_result
      changed_when: create_dev_user_result.rc == 0
      no_log: true

    - name: Cria usuário homolog
      ansible.builtin.shell: >
        mysql -u root -p{{ mysql_root_password }} -e "
            CREATE USER IF NOT EXISTS 'abnmo_qa'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ lookup('file', 'secrets/abnmo_qa_pwd.txt') }}';
            GRANT DELETE, INSERT, SELECT, UPDATE ON abnmo_qa.* TO 'abnmo_qa'@'%';
            FLUSH PRIVILEGES;"
      register: create_qa_user_result
      changed_when: create_qa_user_result.rc == 0
      no_log: true

    - name: Atualiza DNS Dinâmico (freedns.afraid.org) - ipecode-dev-db.ignorelist.com
      ansible.builtin.uri:
        url: "{{ lookup('file', 'secrets/freedns_update_url.txt') }}"
        method: GET
        status_code: 200
        return_content: true
      changed_when: false
      no_log: true

  handlers:
    - name: Recarregar tabelas de privilégios
      ansible.builtin.command: mysqladmin flush-privileges
      environment:
        MYSQL_PWD: "{{ mysql_root_password }}"
      changed_when: false

  vars:
    mysql_root_password: "{{ lookup('file', 'secrets/root_pwd.txt') }}"
